const DataTelTab = [
  {
    id: "1",
    catégorie: "téléphone portable",
    produit: "smartphone",
    nomProduit: "xiomiRedmi Note12/4GO/128GO/Vert",
    img: "../images/smartphone-xiaomi-redmi-note-12-4-go-128-go-vert.jpg",
    description:
      "Double Sim - Ecran 6.67AMOLED DotDisplay Taux de rafraîchissement de 120 Hz Résolution Full HD+ : 1080 x 2400 pixels  Processeur Snapdragon 685 8 cœurs ( jusqu'à 2,8 GHz ) - RAM 4 Go - Mémoire 128 Go - Android 13 Avec MIUI 14 - Appareil Photo 50 MP (f/1.8) + 8 MP (Caméra ultra grand-angle, f/2.2, FOV 120°) + 2 MP (Objectif macro, f/2.4) - Caméra frontale de 13 MP (f/2,45) - Réseau 4G - BlueTooth 5.0 - Wi-Fi - USB Type C - Capteur d'empreintes digitales latéral - Reconnaissance faciale - GPS - Résistance à l'eau et à la poussière IP53 - Batterie 5000 mAh - Charge rapide 33W - carte microSD - Couleur Vert - Garantie 1 an",
    marque: "XiomiRedmi",
    prix: "716.000TND",
    rating: "4",
  },
  {
    id: "2",
    catégorie: "accessoires téléphonique",
    produit: "casque et ecouteurs",
    nomProduit: "Inkax Ecouteur Sans fils T3 - Bluetooth",
    img: "../images/ecouteur.jpg",
    description:
      "Ecouteur Sans fils T3 - BluetoothVous avez besoin d'une paire d'écouteurs d'entrée de gamme avec un bon rapport qualité prix et facile à utiliser , voici ce que nous vous proposons: de très simples écouteurs pour écouter à la musique et passer vos appels téléphoniques. Qualité de son stéréo réelle avec des basses profondes : Bluetooth 5.0 amélioré et technologie de rendu HD sans perte qui produit une qualité sonore incroyable avec des basses profondes. Mode mono-auriculaire binaural : les deux écouteurs peuvent fonctionner ensemble ou séparément pour deux personnes et se connecter à différents appareils Bluetooth. Appareils compatibles avec une antenne haute sensibilité jusqu'à 10 mètres de distance.",
    marque: "Inkax",
    prix: "38.90 TND",
    rating: "3.5",
  },
  {
    id: "3",
    catégorie: "téléphone portable",
    produit: "smartphone",
    nomProduit: "XIAOMI Smartphone REDMI 10 2022 (4/64Go) Bleu",
    img: "../images/xiaomi_smartphone_redmi_10_2022_3.png",
    description:
      "Écran 6,5 Pouce 90Hz Corning Gorilla Glass 3 / Résolution : 1080x2400 pixels / Mémoire RAM : 4Go / Stockage : 64Go / Système d'exploitation : Android 11, MIUI 12,5/ Processeur : Octa-core 2.0 Ghz Cortex-A75 / Appareil Photo Principale : 50Mpx + 8Mpx + 2Mpx + 2Mpx / Selfie : 8Mpx / Connectivité : Wi-Fi - Bluetooth 5.1 - GPS - USB Type-C 2.0 / Batterie : 5000 mAh / Autonomie : 30 heures des appels - 14 heures de vidéos - 14 heures de vidéos / Dimension : 75.5X161.9X8.9mm / Poids : 181g / Garantie 1 an.",
    marque: "XiomiRedmi",
    prix: "799,000 TND",
    rating: "3.5",
  },
  {
    id: "4",
    catégorie: "tablette",
    produit: "tabletteEducatif",
    nomProduit: "TABLETTE HUAWEI MATEPAD SE 10.4' / 4 GO / 64 GO / NOIR",
    img: "../images/tablette-huawei-matepad-se-104-4-go-64-go-noir.jpg",
    description:
      "Ecran 10,4 IPS - Résolution 2000 × 1200p Processeur Octa Core HUAWEI Qualcomm Snapdragon 680 (4 × Cortex-A73 2,4 GHz + 4 × Cortex-A53 1,9 GHz) - Processeur Graphique Adreno 610 - Système d’exploitation HarmonyOS 3 - RAM 4 Go - Mémoire 64 Go - Deux haut-parleurs (HUAWEI Histen 8.0) - 2x Appareils Photo: 5MP F2.2 AutoFocus (Arrière), 2 MP F/2.4 (Frontale) - Batterie 5100 mAh - 4G - Wifi - Bluetooth - Dimensions 246,94 x 156,7 x 7,85 mm - Couleur Noir - Garantie 1 an ",
    marque: "HUAWEI",
    prix: "699,000 TND",
    rating: "3",
  },
  {
    id: "5",
    catégorie: "tablette",
    produit: "accessoire tablette",
    nomProduit: "Etui tablette 7″ Cuire Rose",
    img: "../images/etui-tablette-7-cuire-rose-prix-tunisie.jpg",
    description:
      "Protégez efficacement votre tablette grâce à cette coque antichoc universelle. Une coque robuste et qui vous accompagne au quotidien.Pratique, vous pouvez le glisser dans votre poche / sac.La conception mince s'adapte parfaitement pour garder votre tablette dans les perspectives de style. Il suffit de l'encliqueter pour l'installer et l'enlever facilement. ",
    marque: "",
    prix: "13,00 TND",
    rating: "4",
  },
  {
    id: "6",
    catégorie: "accessoires téléphonique",
    produit: "accessoire pour selfie",
    nomProduit: "Tige pour selfie Bluetooth",
    img: "../images/tige-pour-selfie-bluetooth-prix-tunisie.jpg",
    description:
      "Une fixation à ressort offre un maintien solide Connexion directe par Bluetooth avec le smartphone",
    marque: "Samsung",
    prix: "99,00 TND ",
    rating: "4.5",
  },
  {
    id: "7",
    catégorie: "accessoires téléphonique",
    produit: "casque et ecouteurs",
    nomProduit: "ÉCOUTEURS BLUETOOTH SANS FIL QCY TWS NOIR (QCY-T17-BK)",
    img: "../images/ecouteurs-bluetooth-sans-fil-qcy-tws-noir-qcy-t17-bk.jpg",
    description:
      "Écouteurs Bluetooth Sans Fil QCY T17 - Technologie de connectivité: Bluetooth 5.1 - Autonomie : 26 heures - Autonomie de la batterie : 4,5 heures d’appel ; 7.5 heures Son HiFi, latence ultra-faible, suppression du bruit ENC pour les appels - Ajustement confortable  - Etui de chargement, 3 paires d’embouts, 1 câble de type C, 1 manuel d’utilisation - Portée de fonctionnement : 10 m - Couleur: Noir",
    marque: "",
    prix: "79,000 TND",
    rating: "5",
  },
  {
    id: "8",
    catégorie: "accessoires téléphonique",
    produit: "accessoire pour selfie",
    nomProduit: "LT POWER Support selfie - 360°",
    img: "../images/tige2.jpg",
    description:
      "Le support de caméra à suivi automatique tourne à 360 degrés et reconnaît automatiquement les personnes ou même les objets. De plus, lorsqu’il est connecté à votre smartphone, il se tourne vers l’endroit où vous voulez aller puis définit la pose et prend automatiquement des photos ou vidéos. Idéal pour les conférences, les événements sportifs mais également pour Instagram, Youtube et Tiktok. Il peut se fixer à une perche ou un trépied, ce qui vous permet de donner de la hauteur et de s’adapter aux différentes situations. Support rotatif pour prendre des photos ou vidéos à 360° Compatible avec les principaux smartphones, tablettes et tout type de tables",
    marque: "",
    prix: "39.000TND",
    rating: "3.5",
  },
  {
    id: "9",
    catégorie: "accessoires téléphonique",
    produit: "accessoire pour voiture",
    nomProduit:
      "Support Téléphone Universel Pour Voiture 360° Degrée Easy One Touch",
    img: "../images/data acc voiture  .jpg",
    description:
      "Support ajustable et flexible Rotatif 360° Maintient en toute sécurité des appareils de 2,3 à 3,5 pouces Le support est facilement réglable",
    marque: "",
    prix: "25 TND",
    rating: "3",
  },
  {
    id: "10",
    catégorie: "accessoires téléphonique",
    produit: "casque et ecouteurs",
    nomProduit: "CASQUE SOG XPERT H1500 RGB - WIRELESS BLUETOOTH",
    img: "../images/casque-sog-xpert-h1500-rgb-wireless-bluetooth.jpg",
    description:
      "Casque Spirit Of Gamer XPERT H1500, RGB Connectivité: Sans Fil 2,4 GHz, Bluetooth, Haut-parleurs 50 mm et son Surround 7.1, Batterie: Lithium de 1000 mAh offre une autonomie de 20 H (sans RGB / Volume 50%) et se charge en 3 heures, Connectiques: télécommande intégrée sur l’écouteur (contrôler : le volume ±, mute microphone), Prises jack (pour utilisation filaire), USB-C (pour recharger).",
    marque: "Spirit Of Game",
    prix: "219,000DT",
    rating: "3",
  },
  {
    id: "11",
    catégorie: "accessoires téléphonique",
    produit: "accessoire pour voiture",
    nomProduit:
      "Qianyou Support Téléphone Voiture, Porte Téléphone Voiture Magnétique Pliable Universel",
    img: "../images/porte tel mag.jpg",
    description:
      "Accessoires Voiture pour iphone, Samsung, Huawei 【Aimant Puissant Amélioré】Le support de téléphone de voiture magnétique universel a un aimant d'aspiration fort intégré, qui maintient fermement le téléphone et ne tombe jamais. Le support de téléphone mobile de voiture est de petite taille et fournit un grand champ magnétique fermé, qui n'affectera pas le signal du téléphone mobile. Le support magnétique de téléphone de voiture super facile à utiliser libère complètement vos mains et assure votre sécurité de conduite.",
    marque: "",
    prix: "48.000 TND",
    rating: "4.5",
  },
  {
    id: "12",
    catégorie: "tablette",
    produit: "accessoire tablette",
    nomProduit: "Etui tablette adaptable 9'Blanc",
    img: "../images/etui blannc.jpg",
    description:
      "Cette housse rigide à combinaison de couleurs offre une protection parfaite contre les rayures à l'arrière et sur les côtés de votre téléphone mobile. En raison de son excellente conception, il s'adapte librement sur votre smartphone en un clic. De plus, toutes les fonctions sont accessibles et ne sont pas bloquées par le boîtier.Etui Pour Tablette 8' bleu- Matière Intérieure Pour Protection De L'écran - Système De Fixation . Malgré la bonne protection, un film protecteur est recommandé pour l'écran. ",
    marque: "",
    prix: "8.98 TND",
    rating: "5",
  },
  {
    id: "13",
    catégorie: "accessoires téléphonique",
    produit: "casque et ecouteurs",
    nomProduit: "Casque Bluetooth Spirit Blanc orange",
    img: "../images/Casque-Bluetooth-Spirit-Blanc-orange-BestBuy-tunisie.webp",
    description:
      "Bande de fréquences: 2402-2480MHz –Bande passante (Casque): 20 Hz – 20 kHz Bande passante (Microphone) :100 Hz – 10 kHz Classe Bluetooth: Classe 2",
    marque: "Best Buy Tunisie",
    prix: "99.000 TND",
    rating: "3.8",
  },
  {
    id: "14",
    catégorie: "tablette",
    produit: "tabletteEducatif",
    nomProduit: "TABLETTE SAMSUNG GALAXY TAB 6 A SM-T295 / 10.5' ",
    img: "../images/tablette-samsung-galaxy-tab-a-sm-t295-4g-8-32-go-silver.jpg",
    description:
      "Ecran 10.5' Super Amoled (2560 x 1600) - ProcesseurQualcomm Snapdragon Octa Core 855, 2.8 GHz - Android Android 9.0 - RAM 8 Go - Mémoire 128 Go extensible jusqu’à 512Go - Appareil Photo: 13 + 5 MP avec autofocus, ouverture f/2 + f/2.2, panorama / Caméra frontale de 8 MP avec contrôle par mouvement / Vidéo Ultra HD 30 fps - 4G - Bluetooth - Wifi - GPS - Bluetooth - Batterie 7040 mAh  - Garantie 1 an",
    marque: "Samsung",
    prix: "2699,000 TND",
    rating: "4.5",
  },
  {
    id: "15",
    catégorie: "téléphone portable",
    produit: "smartphone",
    nomProduit: "Samsung Galaxy A24 6go 128go 4G Silver",
    img: "../images/samsung-galaxy-a24-6go-128go-4g-silver.webp",
    description:
      "Smartphone Samsung Galaxy A24 6go 128go 4G Silver En Tunisie avec Garantie officielle et Livraison Gratuite Ecran: 6,5 pouces FHD+ Super AMOLED (1080x2340) pixelsProcesseur: Mediatek MT8781 Hélio G99 (6nm) Octa Core (Cortex-A76 2x2,2 GHz et Cortex-A55 6x2,0 GHz) Système d'exploitation: Android 13, ONE UI 5.1 Mémoire RAM : 6go Capacité de Stockage: 128go Appareil Photo Avant: 13 mégapixels Appareil Photo Arrière: 50 mégapixels+5 mégapixels +2 mégapixels Batterie: 5000mAh Connectivités: 4G Nombre de SIM: Double SIM Empreinte Digitale Garantie:1 an ",
    marque: "Samsung",
    prix: "1059,000 TND",
    rating: "3",
  },
  {
    id: "16",
    catégorie: "téléphone portable",
    produit: "smartphone",
    nomProduit: "Samsung Galaxy Note 20 Ultra",
    img: "../images/samsung-galaxy-note-20-ultra-tunisie.jpg",
    description:
      " 6,9 Super amoled+ Définition 3088 x 1440 pixels. Technologie d'affichage Super AMOLED+. Fréquence d'affichage 120 images par seconde. Mémoire 8Go Stockage 256Go Caméra avant 10.0 MP Caméra arrière 12.0 MP + 16.0 MP + 108.0 MP Batterie 4500 mAh 8K video",
    marque: "Samsung",
    prix: "3750,00 TND",
    rating: "5",
  },
  {
    id: "17",
    catégorie: "téléphone portable",
    produit: "smartphone",
    nomProduit: "iPhone 14 Pro Max, 128Gb - Gold",
    img: "../images/iphone 14 pro.jpg",
    description:
      "iPhone 14 Pro Max. Capture incredible detail with a 48MP Main camera. Experience iPhone in a whole new way with Dynamic Island and Always-On display. Crash Detection,1 a new safety feature, calls for help when you can’t",
    marque: "Apple",
    prix: "4000.000",
    rating: "5",
  },
  {
    id: "18",
    catégorie: "téléphone portable",
    produit: "smartphone",
    nomProduit: "IPHONE 13 128GO STARLIGHT",
    img: "../images/iph-13.jpg",
    description:
      "Ecran 6,1 OLED Super Retina XDR HDR - Résolution: 2532 x 1170 pixels à 460 ppp - Processeur:  Puce A15 Bionic (5 nm) Hexa-core ( 2 x 3.22 GHz Avalanche + 4 x X.X GHz Blizzard) - GPU Graphics Apple 4 Coeurs - Système d'exploitation: iOS 15 - Mémoire RAM: 4 Go - Stockage: 128 Go - Appareil photo Arrière: Dual Pixels: 12 MégaPixels Grand‑angle avec ouverture ƒ/1,6 + 12 MégaPixels Ultra grand‑angle avec ouverture ƒ/2,4 et champ de vision de 120° - Appareil Avant: 12 MégaPixels avec Ouverture ƒ/2,2 - Video 4K HDR avec Wifi, Réseau 5G , GPS , NFC et Bluetooth 5.0 - Batterie: Li-Ion 3240 mAh - Face ID - Couleur: Starlight - Garantie: 1 an",
    marque: "Apple",
    prix: "3299,000 DT",
    rating: "4.5",
  },
];
export default DataTelTab;
